### ISSUE TITLE
Fallback to ffmpeg if avconv not found

### ISSUE THREAD

**Issue by noffle** [binarykitchen/avconv#5]
Handy for those of us who didn't opt into the avconv fork.

Underlying assumption: the accepted params for the two are close enough that this would be transparent.
##

**Comment by noffle** [comment]
I experimented with this a bit, but it's a bigger job than I thought. This module is very tightly coupled to `avconv`'s stderr output, to the point that tests fail when I substitute in `ffmpeg`.

It might make more sense to write a separate `ffmpeg` module, and have an `abstract-video-conversion-stream` that falls back to either `avconv` or `ffmpeg` depending on what's available.

Let me know if you have any thoughts on this!

**Comment by binarykitchen** [comment]
Interesting request. But I'm not sure if it's a good idea because both commands require different parameters and emit different events.

Probably better to make a new package which does the detection and delegates the request to the correct library? Keep it simple and have each package do one thing only.

**Comment by noffle** [comment]
Agreed. Something like [fluent ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/README.md), but backend agnostic would be great.

**Comment by noffle** [comment]
Aside: ah ha, looks like [you've already been down this unpleasant road](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/106).

**Comment by binarykitchen** [comment]
oh yes

**Comment by binarykitchen** [comment]
@noffle https://github.com/binarykitchen/avconv/pull/8 should please you

**Comment by noffle** [comment]
:heart:! I love it when excellent open source folks suddenly pull through like this out of the blue. :tada:
