### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by amilajack** [binarykitchen/avconv#7]
Using this library, would I be able to parse an mkv file and convert this to mp4 at runtime?

**Comment by binarykitchen** [comment]
@amilajack Anything you can command `avconv ...` via command-line is possible with this npm module too. In other words, do you have an avconv command handy to parse a mkv file?

**Comment by amilajack** [comment]
Oh right, that was what I mean to ask.

**Comment by binarykitchen** [comment]
@amilajack If you are after the correct avconv command to parse a mkv file then I would begin with stackoverflow first and test it via command line before you use this npm module
